몇몇 디자인 요소 수정
wakscord/extension pull request #17
Opened 2023-05-28 13:22 UTC by So-chiru

- Splash 스크린 색상 변경 (배경에 맞도록), Fade Out 애니메이션 추가, 로고 사이즈 수정
- 설정 창 애니메이션 Easing 변경
- Info 박스 padding, 글자 크기 수정
- Chats, Info 박스 사이 간격 제거
- 설정 버튼 padding 사이즈 변경

제가 생각하는 개선하면 좋을 부분 멋대로 수정해봤는데 방향성이 안맞다 싶으시면 자유롭게 리젝 때리셔도 됩니다

2023-05-28 13:31 UTC, sudosubin approved these changes
저는 괜찮은 것 같습니다 🙇

2023-05-28 13:35 UTC, minibox24 requested changes
설정 페이지에서의 스크롤 바 하단이 짤립니다

2023-05-28 13:36 UTC, minibox24 requested changes
![image](https://github.com/wakscord/extension/assets/61264156/075dceaf-cd82-4f8a-aa91-28395d9c2057)

스플래시 색깔이 디코색이니 여기도 수정이 필요해보입니다

2023-05-28 13:37 UTC, minibox24 commented
저,,는 설정버튼이 둥둥 떠다니는게 어색해보이긴 해요

2023-06-03 04:57 UTC, minibox24 approved these changes

2023-06-03 05:02 UTC, minibox24 commented
컨플릭트 해결까지 킹아

2023-06-03 05:02 UTC, merged