Refactor (Fix refresh system)
wakscord/extension pull request #21
Opened 2023-06-04 09:36 UTC by sudosubin

## 확인하셨나요?

- [x] Prettier 를 사용해서 코드 포멧팅과 함께 커밋을 하셨나요? 저장 시 코드 포멧팅을 자동으로 해주는 [편집기 확장 설치](https://prettier.io/docs/en/editors.html)를 권장드립니다.
- [x] (선택 사항) [EditorConfig](https://editorconfig.org) 편집기 플러그인 사용하기, 프로젝트 내 편집기 인덴트 설정을 two-space 로 고정해줍니다.
- [x] 타입 체크가 통과되었나요? `yarn tsc` 를 실행하고 오류가 있는 구문을 고쳐주세요.
- [x] ESLint 규칙이 모두 다 통과되었나요? `yarn lint` 를 실행해서 오류가 있는지 확인해주세요.

---

## 주요 변경 사항

- https://github.com/wakscord/extension/pull/20 을 개선합니다.

## 스크린샷

2023-06-04 10:27 UTC, minibox24 requested changes

2023-06-04 10:27 UTC, minibox24 commented on src/hooks/useExtensionChats.ts
> +        return [];
![image](https://github.com/wakscord/extension/assets/61264156/947393d6-7de2-4d47-883d-158405c6349e)

새로고침을 할 때마다 빈 페이지가 생기는 것 같은데 이 부분은 수정이 필요하지 않을까요?

2023-06-04 10:33 UTC, sudosubin commented on src/hooks/useExtensionChats.ts
> +        return [];
맞아요 저도 그 부분이 조금 고민이 되었었는데, 일단은 어쩔 수 없다고 생각하고 놔뒀습니다.
error를 던지면 해결이 될 것 같긴 한데.. 고민이 되네요 😢

2023-06-04 10:38 UTC, minibox24 commented on src/hooks/useExtensionChats.ts
> +        return [];
select에서 빈 array를 제거하면 완전히 사라지는건가요? 아니면 어딘가에는 남아있는 채로 최종적으로 보이는거에서만 사라지는건가요??

2023-06-04 10:57 UTC, sudosubin commented on src/hooks/useExtensionChats.ts
> +        return [];
select는 원본 데이터는 그대로 남아있어서 메모리에는 남아있고, hook으로 읽어올 때에만 transform 하는 역할을 합니다.

2023-06-04 11:04 UTC, sudosubin commented on src/hooks/useExtensionChats.ts
> +        return [];
![CleanShot 2023-06-04 at 20 03 22@2x](https://github.com/wakscord/extension/assets/32478597/9bb976c4-9ace-4ae3-828d-dacdc678c41d)

이렇게 error를 던지도록 수정해봤습니다. `NODE_ENV=production` 에서는 이런 로그가 남지 않을 거예요.

2023-06-05 09:44 UTC, minibox24 approved these changes

2023-06-05 09:44 UTC, merged