Implement Api v2
wakscord/extension pull request #4
Opened 2023-05-26 05:34 UTC by minibox24

[ ] 왁물원 게시물 채널별로
[ ] 무한 스크롤에 알 수 없는 문제
[ ] 설정 페이지 바텀에 패딩
[ ] 설정 페이지 텍스트 수정
[ ] 슬라이더가 통통 튐

2023-05-27 13:21 UTC, unsignd reviewed
replace spinner with skeleton

2023-06-03 09:45 UTC, opentypefont commented on src/components/MessagePlaceholder.tsx
여기 절대단위가 사용된 컴포넌트들은 전부 확인해보신건가요?

2023-06-03 09:51 UTC, opentypefont requested changes

2023-06-03 09:51 UTC, opentypefont commented on src/utils.ts
이 파일은 이름을 수정해 utils/ 내부로 이동하는게 좋을 것 같습니다.

2023-06-03 10:10 UTC, opentypefont requested changes
hooks/ 폴더 내 파일 이름의 형식을 통일하면 좋을 것 같아요.

2023-06-03 10:17 UTC, opentypefont requested changes

2023-06-03 10:17 UTC, opentypefont commented on src/components/discord/Badge.tsx
뱃지 컴포넌트는 상대단위를 사용하고 있는데, 다른 컴포넌트들은 전부 절대단위를 사용하고 있어요. 의도된 것이 아니라면 상대단위 또는 절대단위 중 하나로 해주시는게 좋을 것 같아요.

2023-06-03 10:24 UTC, opentypefont reviewed
계속 검토해가면서 진행해 주셔서 몇 가지 사소한 이슈를 제외하고 별다른 문제는 보이지 않아요. 수고하셨습니다 :)

2023-06-03 13:29 UTC, minibox24 commented
자동 새로고침이 켜져있을 시, 채팅의 변경 내용이 없어도 맨 밑으로 내려가집니다

2023-06-04 04:04 UTC, opentypefont approved these changes

2023-06-04 05:29 UTC, So-chiru approved these changes

2023-06-04 06:25 UTC, minibox24 commented on src/components/Chats.tsx
> +          <Refresh onClick={async () => await loadRecentChats(true)} />
@sudosubin https://github.com/wakscord/extension/commit/b2d9b6a512c0a31f9722e9e4547bde927ee72227

2023-06-04 06:33 UTC, sudosubin commented on src/components/Chats.tsx
> +          <Refresh onClick={async () => await loadRecentChats(true)} />
Outdated 이라서 간단히 답변 드리면 큰 이유는 없었고, 작업하는 과정에서 여러 interface 갈아끼우면서 들어갔을 것 같네요. 저기에 잠시 function body를 넣었던 적이 있어서 남았을 거 같습니다.

2023-06-04 06:59 UTC, x86chi commented on docs/pull_request_template.md
main 브랜치에도 .github 경로에 `pull_request_template.md` 가 만들어져서(1bb780368bba601accda1324f8b6b8518fc50b04) 둘 중 하나를 삭제해야 됩니다. 

`VITE_CHANNEL_ID` 환경변수 소개를 위한 기여 가이드 문서도 작성이 필요해서 아래처럼 docs 폴더로 옮겨 같이 관리하는 게 어떨까요?

> [Setting guidelines for repository contributors](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)

> - docs
>   - pull_request_template.md
>   - CONTRIBUTING.md

2023-06-04 07:07 UTC, minibox24 commented on docs/pull_request_template.md
좋습니다! 혹시 대신 `CONTRIBUTING.md`를 작성해주실 수 있으신가요?

2023-06-04 07:11 UTC, x86chi commented on docs/pull_request_template.md
넵~

2023-06-05 12:17 UTC, choshinyoung approved these changes

2023-06-05 12:17 UTC, unsignd approved these changes
잘했어요!

2023-06-05 12:31 UTC, sudosubin approved these changes

2023-06-05 12:47 UTC, sandsunset approved these changes

2023-06-06 06:01 UTC, x86chi approved these changes
👍🏻

2023-06-12 11:58 UTC, merged